// frontend/src/pages/LoginPage/index.tsx
// Type
import type { API_LoginData } from '@/service/user-api';

// Router
import { useHistory, useLocation } from 'react-router-dom';
// Recoil
import { useRecoilState } from 'recoil';
import { A_User } from '@/store';

// Hooks
import { useCreation, useRequest } from 'ahooks';
// API
import { API_Login } from '@/service/user-api';
// Utils
import { localStorage } from '@/utils';

// Antd component
import { Button, Form, Input, App } from 'antd';

// Scoped style
import classes from './style.module.scss';

export default function LoginPage() {
	const { message: AntdMessage } = App.useApp();
	const history = useHistory();
	const { state: locationState } = useLocation();
	const [user, setUser] = useRecoilState(A_User);

	const loginAsStaff = useCreation(() => {
		// @ts-ignore
		return (locationState?.for && locationState.for) === 'staff';
	}, [locationState]);

	const loginLabel = useCreation(() => {
		// @ts-ignore
		if (loginAsStaff) {
			return 'Қызметші ID немесе телефон нөмер';
		}

		return 'Телефон нөмер';
	}, [loginAsStaff]);

	// Login API
	const { runAsync } = useRequest(API_Login, { manual: true });
	// Login logic
	const onFinish = async (values: Omit<API_LoginData, 'isStaff'>) => {
		const res = await runAsync({ ...values, isStaff: loginAsStaff }).catch(
			error => {
				AntdMessage.error(error.message);
			},
		);

		if (res) {
			AntdMessage.success('Кіру сәтті');
			localStorage.set('user', res);
			setUser(res);
			history.push('/ticket');
		}
	};

	return (
		<main className={classes.loginPage}>
			<h3 className="title">Жүйеге кіру</h3>

			<Form
				className="form"
				layout="vertical"
				autoComplete="off"
				onFinish={onFinish}>
				<Form.Item
					label={loginLabel}
					name="login"
					rules={[
						{ required: true, message: 'Міндетті өріс' },
						{ max: 11, message: '11 таңбадан аспауы керек' },
					]}>
					<Input />
				</Form.Item>

				<Form.Item
					label="Құпия сөз"
					name="password"
					rules={[{ required: true, message: 'Құпия сөз енгізіңіз' }]}>
					<Input.Password />
				</Form.Item>

				<Form.Item>
					<Button
						block
						type="primary"
						htmlType="submit"
						size="large"
						className="primary-btn">
						Кіру
					</Button>
				</Form.Item>
			</Form>
		</main>
	);
}

// const route = useRoute();
// const router = useRouter();
// const { for: userType = 'user' } = route.query;

// const user = useUserStore();

// const formData = reactive({
// 	login: '',
// 	password: '',
// });

// const { runAsync } = useRequest(API_Login, {
// 	manual: true,
// });

// const loginLabel = computed(() => {
// 	if (userType === 'user') {
// 		return 'Телефон нөмер';
// 	}

// 	return 'Қызметкер ID';
// });

// const handleLogin = () => {
// 	runAsync({
// 		...formData,
// 		is_staff: userType !== 'user',
// 	})
// 		.then(({ data }) => {
// 			user.setUser(data);
// 			localStorage.set('user', user.toJson);
// 			router.push('/ticket');
// 		})
// 		.catch(error => {
// 			alert(error.message);
// 		});
// };
// </script>

// frontend/src/pages/LoginPage/index.vue
<template>
	<div class="login-page">
		<h3 class="title">Жүйеге кіру</h3>

		<div class="group">
			<label class="label" for="idInput">{{ loginLabel }}</label>
			<Input
				id="idInput"
				class="field"
				:value="formData.login"
				@change="value => (formData.login = value)"
			/>
		</div>

		<div class="group">
			<label class="label" for="passwordInput">Құпия сөз</label>
			<Input
				id="passwordInput"
				class="field"
				type="password"
				:value="formData.password"
				@change="value => (formData.password = value)"
			/>
		</div>

		<Button class="primary-btn" @click="handleLogin">Кіру</Button>
	</div>
</template>

<script setup lang="ts">
import { reactive, computed } from 'vue';
// Router
import { useRoute, useRouter } from 'vue-router';
// Hooks
import { useRequest } from 'vue-hooks-plus';
// Store
import { useUserStore } from '@/store';
// Utils
import { localStorage } from '@/utils';
// Component
import Input from '@/components/Input/index.vue';
import Button from '@/components/Button/index.vue';
// Service
import { API_Login } from '@/service/user-api';

const route = useRoute();
const router = useRouter();
const { for: userType = 'user' } = route.query;

const user = useUserStore();

const formData = reactive({
	login: '',
	password: '',
});

const { runAsync } = useRequest(API_Login, {
	manual: true,
});

const loginLabel = computed(() => {
	if (userType === 'user') {
		return 'Телефон нөмер';
	}

	return 'Қызыметкер ID';
});

const handleLogin = () => {
	runAsync({
		...formData,
		is_staff: userType !== 'user',
	})
		.then(({ data }) => {
			user.setUser(data);
			localStorage.set('user', user.toJson);
			router.push('/ticket');
		})
		.catch(error => {
			alert(error.message);
		});
};
</script>

<style scoped lang="scss">
@import '@/assets/style/mixins.scss';

.login-page {
	width: 100%;
	padding: 0 16px;

	@include centerPositioned($top: 40%);
	@include flex($direction: column, $alignItems: center);

	.title {
		font-size: 40px;
		font-weight: 700;
		margin-bottom: 32px;
	}

	.group,
	.group .field,
	.primary-btn {
		width: 100%;
	}

	.group {
		@include flex($direction: column, $gap: 4px);
		margin-bottom: 16px;
	}

	.primary-btn {
		margin-top: 16px;
	}
}
</style>
